checks:
  php: true

filter:
  paths: ['src/*']

build:
  environment:
    php:
      version: 7.0
  checks:
    before:
      - "cp composer.lock.example composer.lock"
      - "composer install --dev"
