version: "2"
services:
    phinx:
        build: .
        volumes:
            - .:/src
        links:
            - mysql
            - postgres
        command: sh -c "cd /src && `cat phpunit.xml.dist | sed 's/localhost/mysql/' | sed 's/127.0.0.1/postgres/' > phpunit.xml` && /bin/bash"
    mysql:
        image: mysql:5.5
        environment:
            - MYSQL_DATABASE=phinx_testing
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    postgres:
        image: postgres:9.2
        environment:
            - POSTGRES_DB=phinx_testing

