version: "2"
services:
    phinx:
        build: .
        volumes:
            - .:/src
        links:
            - mysql
            - postgres
        command: bash
        environment:
            - TESTS_PHINX_DB_ADAPTER_MYSQL_HOST=mysql
            - TESTS_PHINX_DB_ADAPTER_POSTGRES_HOST=postgres
    mysql:
        image: mysql:5.6
        environment:
            - MYSQL_DATABASE=phinx
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - 3306:3306

    postgres:
        image: postgres:9.4
        environment:
            - POSTGRES_DB=phinx
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
