name: Upload Release PHAR

on:
  release:
    types: [published]

jobs:
  build:
    name: Upload Release PHAR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist

      - run: composer global require humbug/box:^3.8

      # We need to set symfony/yaml as regular dependency so box packs it
      - run: composer require symfony/yaml

      - name: Compile PHAR
        run: ~/.composer/vendor/bin/box compile

      - name: Upload Release Asset
        uses: actions/github-script@v8
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const fs = require('fs').promises;
            await github.rest.repos.uploadReleaseAsset({
              name: 'phinx.phar',
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              data: await fs.readFile('./phinx.phar')
            });
